swagger: "2.0"
info:
  description: "CS Desafio Node"
  version: "1.0.0"
  title: "CS Desafio"
basePath: "/api"
consumes:
  - "application/json"
produces:
  - "application/json"
schemes:
- "http"
paths:
  /check:
    get:
      tags:
        - Health
      description: "Check if server is alive"
      operationId: "checkGET"
      responses:
        204:
          description: "No content"
      x-swagger-router-controller: "Default"

  /user:
    post:
      tags:
        - User
      description: "Register new user"
      operationId: "userPOST"
      parameters:
        - in: body
          name: Registration Model
          description: User registration model
          required: true
          schema:
            $ref: "#/definitions/Register"
      responses:
        201:
          description: "Created"
          schema:
            $ref: "#/definitions/User"
        400:
          description: "Bad Request"
      x-swagger-router-controller: "Default"

    put:
      tags:
        - User
      description: "Login user"
      operationId: "userPUT"
      parameters:
        - in: body
          name: Login Model
          description: User login model
          required: true
          schema:
            $ref: "#/definitions/Login"
      responses:
        200:
          description: "Sucess"
          schema:
            $ref: "#/definitions/User"
        400:
          description: "Bad Request"
        401:
          description: "Unauthorized"
      x-swagger-router-controller: "Default"

  /user/{id}:
    get:
      tags:
        - User
      description: "Get user"
      operationId: "userGET"
      parameters:
        - in: path
          name: id
          description: User id
          required: true
          type: string
        - in: header
          name: authorization
          description: Bearer Token
          type: string
          required: true
      responses:
        200:
          description: "Sucess"
          schema:
            $ref: "#/definitions/User"
        400:
          description: "Bad Request"
        401:
          description: "Unauthorized"
      x-swagger-router-controller: "Default"

definitions:
  Login:
    type: "object"
    properties:
      email:
        type: "string"
      senha:
        type: "string"

  Register:
    type: "object"
    properties:
      nome:
        type: "string"
      email:
        type: "string"
      senha:
        type: "string"
      telefones:
        type: "array"
        items:
          $ref: "#/definitions/Telefone"

  User:
    type: "object"
    properties:
      id:
        type: "string"
      nome:
        type: "string"
      email:
        type: "string"
      telefones:
        type: "array"
        items:
          $ref: "#/definitions/Telefone"
      data_criacao:
        type: "string"
      data_atualizacao:
        type: "string"
      ultimo_login:
        type: "string"
      token:
        type: "string"

  Telefone:
    type: "object"
    properties:
      numero:
        type: "number"
      ddd:
        type: "number"